{% set name = "libsvmdata" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/libsvmdata-{{ version }}.tar.gz
  sha256: 292b675ce8ea363dfbf7d32b4b6a5e13b59b74ffff545a2198237270da710e46

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - download
    - numpy >=1.12
    - python >=3.6
    - scikit-learn
    - scipy

test:
  imports:
    - libsvmdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/libsvmdata/
  summary: Fetcher for LIBSVM datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfansler
