{% set name = "libsvmdata" %}
{% set version = "0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/libsvmdata-{{ version }}.tar.gz
  sha256: 02d15b169a06df4b7d4d188f023db8a57245f30e6430db2e9f8d8ccff016dbc4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - download
    - numpy >=1.12
    - python >=3.6
    - scikit-learn
    - scipy

test:
  imports:
    - libsvmdata
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/libsvmdata/
  summary: Fetcher for LIBSVM datasets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mfansler
